package ${entity.javaPackage};

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

<#list entity.unBaseTypes as type>
import ${type};
</#list>

/**
 * This code is generated by Aiutool
 * @author aiyouv
 */

@Setter
@Getter
@Entity
@Table(name = "${entity.tableName}")
public class ${entity.className}<#if entity.superclass?has_content> extends ${entity.superclass} </#if> implements Serializable {

<#list entity.properties as property>
    <#if property.description?has_content>
    //${property.description}
    </#if>
    <#if property.identity>
    @Id
    </#if>
    private ${property.javaType} ${property.propertyName};

</#list>
}